api/urls.py
from django.urls import path

import api.views as views


urlpatterns = [
    path('marks/add', views.add_mark, name='marks_add'),
    path('lessons/add', views.add_lesson, name='lessons_add'),
    path('attendance/add', views.add_attendance, name='attendance_add'),
    path('attendance/set', views.set_attendance, name='attendance_set'),
    path('penalty/add', views.add_penalty, name='penalty_add'),
    path('duty/add', views.add_duty, name='duty_add'),
    path('event/add', views.add_event, name='event_add'),
    path('event/set', views.set_event, name='event_set'),
    # path("<int:user_id>", views.borrower_page, name="borrower_page")
]

djour/urls.py
from django.contrib import admin
from django.urls import path, include
from djour.views import journal_index_redirect
from django.conf import settings
from django.conf.urls.static import static
from journal import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path("journal/", include("journal.urls")),
    path("", journal_index_redirect),
    path('api/', include("api.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

journal/urls.py
from django.urls import path
from journal import views

urlpatterns = [
    path('', views.index, name='index'),
    path('students/', views.students, name='students'),
    path('events/', views.events, name='events'),
    path('students/<int:student_id>', views.student, name='student'),
    path('marks/<str:squad_code>/<int:subject_id>', views.marks_squad, name='marks_squad'),
    path('attendance/', views.attendance, name='attendance'),
    path('attendance/<int:attendance_id>', views.edit_attendance, name='attendance_edit'),
    path('squad/<str:squad_code>', views.squad_stats, name='squad_stats'),
]

journal/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = True` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from image_cropping import ImageRatioField



# from journal.managers.marks import student_short_name


class Attendance(models.Model):
    """ строевая записка"""
    date = models.DateField(blank=True, null=True, verbose_name='Дата')
    squad = models.ForeignKey('journal.Squad', models.CASCADE, blank=False, null=True, verbose_name='Взвод')
    students = models.ManyToManyField('journal.StudentAttendance', verbose_name='Студенты')


    @property
    def absent(self):
        return len(self.students.filter(value__iregex='(absent|truant)'))


    @property
    def datestr(self):
        return self.date.strftime("%Y%m%d%H%M%s")


    def __str__(self):
        return f'Строевая записка {self.squad.code} от {self.date.strftime("%Y-%m-%d")}'


    class Meta:
        managed = True
        db_table = 'attendance'
        verbose_name = 'Строевая записка'
        verbose_name_plural = 'Строевая записка'
        constraints = [
            models.UniqueConstraint(fields=('date', 'squad'), name='date/squad pair')
        ]



class StudentAttendance(models.Model):
    student = models.ForeignKey('journal.Student', models.CASCADE)
    value = models.CharField(max_length=20, blank=True, null=True)


    class Meta:
        managed = True



class StudentAttendanceType(models.Model):
    value = models.CharField(max_length=100, blank=True, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)


    class Meta:
        managed = True
        db_table = 'attendance_types'



class Duty(models.Model):
    DUTY = 'duty'
    DETENTION = 'detention'
    CHOICES = (
        (DUTY, 'дежурство'),
        (DETENTION, 'наряд'),
    )

    student = models.ForeignKey('journal.Student', models.CASCADE)
    type = models.CharField(
        'Вид',
        max_length=20,
        choices=CHOICES,
        default=DUTY,
    )
    attendance = models.ForeignKey(Attendance, models.CASCADE, blank=True, null=True, verbose_name="Дата")
    mark = models.IntegerField(blank=True, null=True)
    comment = models.CharField(max_length=100, blank=True, null=True)


    @property
    def russian_type(self):
        if self.type == self.DETENTION:
            return self.CHOICES[1][1]
        return self.CHOICES[0][1]


    class Meta:
        managed = True
        db_table = 'duties'



#
# class DutyType(models.Model):
#     name = models.CharField(unique=True, max_length=100)
#
#     class Meta:
#         managed = True
#         db_table = 'duty_types'


class EventParticipant(models.Model):
    student = models.ForeignKey('journal.Student', models.CASCADE, verbose_name='Студент')
    event = models.ForeignKey('journal.Event', models.CASCADE, blank=True, null=True, verbose_name='Мероприятие')


    class Meta:
        managed = True
        db_table = 'event_participants'
        verbose_name = 'Участник мероприятия'
        verbose_name_plural = 'Участники мероприятия'



class Event(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    date = models.DateField(verbose_name='Дата')


    class Meta:
        managed = True
        db_table = 'events'
        verbose_name = 'Мероприятие'
        verbose_name_plural = 'Мероприятия'



class Exam(models.Model):
    SEMESTER_CHOICES = (
        (3, 3),
        (4, 4),
        (5, 5),
        (6, 6),
        (7, 7),
        (8, 8)
    )
    NAME_EXAM = 'exam'
    NAME_TEST = 'test'
    NAME_CHOICES = (
        (NAME_EXAM, 'Экзамен'),
        (NAME_TEST, 'Зачёт'),
    )
    """ Экзамен """
    subject = models.ForeignKey('journal.Subject', models.CASCADE, db_column='subject', verbose_name='Предмет')
    semester = models.IntegerField('Семестр', choices=SEMESTER_CHOICES, default=0)
    squad = models.ForeignKey('journal.Squad', models.CASCADE, verbose_name='Взвод', null=True)
    name = models.CharField('Форма контроля', max_length=100, choices=NAME_CHOICES, default="")


    @property
    def russian_name(self):
        if self.name == self.NAME_EXAM:
            return self.NAME_CHOICES[0][1]
        elif self.name == self.NAME_TEST:
            return self.NAME_CHOICES[1][1]
        return f'<{self.name}>'


    def __str__(self):
        return f'({self.squad.code}) {self.russian_name} по {self.subject.short} в {self.semester} семестре'


    def display(self):
        return f'{self.russian_name} по {self.subject.short}, {self.semester} семестр'


    class Meta:
        managed = True
        db_table = 'exams'
        verbose_name = 'Форма контроля'
        verbose_name_plural = 'Формы контроля'
        constraints = [
            models.UniqueConstraint(fields=('semester', 'subject', 'squad'), name='max_one_per_semester')
        ]



class Mark(models.Model):
    student = models.ForeignKey('journal.Student', models.CASCADE, blank=True, null=True)
    # teacher = models.ForeignKey('journal.Teacher', models.CASCADE, blank=True, null=True)
    # subject = models.ForeignKey('journal.Subject', models.CASCADE, blank=True, null=True)
    val = models.IntegerField(blank=True, null=True, verbose_name='Оценка')
    lesson = models.ForeignKey('journal.Lesson', models.CASCADE, blank=True, null=True, verbose_name='Предмет')


    class Meta:
        managed = True
        db_table = 'marks'


    def __str__(self):
        return f'{self.val} по {self.lesson.subject.short} ({self.student.short})'


    @property
    def to_display(self):
        return


    @property
    def from_display(self):
        pass



class Penalty(models.Model):
    REPRIMAND = 'reprimand'
    PROMOTION = 'promotion'
    CHOICES = (
        (REPRIMAND, 'взыскание'),
        (PROMOTION, 'поощрение'),
    )
    type = models.CharField(
        'Вид',
        max_length=20,
        choices=CHOICES,
        default=REPRIMAND,
    )
    comment = models.CharField(max_length=256, blank=True, null=True, verbose_name='Комментарий')
    student = models.ForeignKey('journal.Student', models.CASCADE, verbose_name='Студент')
    attendance = models.ForeignKey(Attendance, models.CASCADE, blank=True, null=True, verbose_name='Строевая записка')


    @property
    def russian_type(self):
        if self.type == self.PROMOTION:
            return self.CHOICES[1][1]
        return self.CHOICES[0][1]


    def __str__(self):
        return f'{self.student.short} {self.russian_type} от {self.attendance.date.strftime("%Y-%m-%d")}'


    class Meta:
        managed = True
        db_table = 'penalties'
        verbose_name = 'Дисциплинарная практика'
        verbose_name_plural = 'Дисциплинарные практики'



class Squad(models.Model):
    code = models.CharField(unique=True, max_length=4, blank=True, null=True, verbose_name='Номер')


    class Meta:
        managed = True
        db_table = 'squads'
        verbose_name = 'Взвод'
        verbose_name_plural = 'Взвода'


    def __str__(self):
        return f'{self.code}'



class Student(models.Model):
    UNIT_CHOICES = ((1, 1), (2, 2), (3, 3))
    last_name = models.CharField('Фамилия', max_length=50, blank=True, null=True)
    first_name = models.CharField('Имя', max_length=50, blank=True, null=True)
    middle_name = models.CharField('Отчество', max_length=50, blank=True, null=True)
    squad = models.ForeignKey(Squad, models.CASCADE, blank=True, null=True, verbose_name='Взвод')
    unit = models.IntegerField('Отделение', choices=UNIT_CHOICES, blank=True, null=True)
    journal_id = models.IntegerField('Номер в журнале', blank=True, null=True)
    pic = models.ImageField(upload_to='students_pic/', blank=True, null=True, verbose_name='Изображение')

    cropping = ImageRatioField('pic', '200x300')


    def __str__(self):
        return f'({self.squad.code}) {self.last_name} {self.first_name} {self.middle_name} [{self.id}]'


    @property
    def short(self) -> str:
        def __get0(s: str) -> str:
            if len(s) > 0:
                return s[0]
            return '?'


        return f'{self.last_name} {__get0(self.first_name)}. {__get0(self.middle_name)}.'


    class Meta:
        managed = True
        db_table = 'students'
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'



class Subject(models.Model):
    short = models.CharField('Сокращённое название', max_length=10, blank=True, null=True)
    name = models.CharField('Полное название', max_length=255, blank=True, null=True)


    def __str__(self):
        return f'({self.short}) [{self.id}]'


    class Meta:
        managed = True
        db_table = 'subjects'
        verbose_name = 'Дисциплина'
        verbose_name_plural = 'Дисциплины'



class Teacher(models.Model):
    last_name = models.CharField('Фамилия', max_length=50, blank=True, null=True)
    first_name = models.CharField('Имя', max_length=50, blank=True, null=True)
    middle_name = models.CharField('Отчество', max_length=50, blank=True, null=True)
    rank = models.CharField('звание', max_length=50, blank=True, null=True)


    def __str__(self):
        return f'({self.last_name}) {self.first_name} {self.middle_name} {self.rank} [{self.id}]'


    class Meta:
        managed = True
        db_table = 'teachers'


class Lesson(models.Model):
    # squad = models.ForeignKey(Squad, models.CASCADE, blank=True, null=True)
    subject = models.ForeignKey(Subject, models.CASCADE, blank=True, null=True, verbose_name='Предмет')

api/forms.py
from django import forms
from django.core.exceptions import ValidationError
from journal.models import Duty


class LessonForm(forms.Form):
    name = forms.CharField(label='Название', max_length=100)
    date = forms.CharField(label='Дата', max_length=100)
    subject_id = forms.IntegerField(label='Дисциплина')
    squad_code = forms.CharField(label='Взвод', max_length=100)


class PenaltyForm(forms.Form):
    student_id = forms.IntegerField(label="Студент")
    comment = forms.CharField(label='Комментарий', max_length=100)
    attendance_id = forms.IntegerField(label='День посещения')
    penalty_type = forms.CharField(label="Статус")


class NewAttendanceForm(forms.Form):
    squad_code = forms.CharField(label="Взвод", max_length=4)
    date = forms.DateField(label='Дата')


class SetAttendanceStatusForm(forms.Form):
    student_id = forms.IntegerField(label="Студент")
    attendance_id = forms.IntegerField(label="Записка")
    attendance_type = forms.IntegerField(label="Статус")


class DutyForm(forms.Form):
    student_id = forms.IntegerField(label="Студент")
    comment = forms.CharField(label='Комментарий', max_length=100)
    attendance_id = forms.IntegerField(label='День посещения')
    duty_type = forms.CharField(label="Вид")
    mark = forms.IntegerField(label="Оценка")

    def clean_mark(self):
        mark = self.cleaned_data['mark']
        if mark < 1 or mark > 5:
            raise ValidationError('Invalid mark value', code='invalid')
        return mark


class NewEventForm(forms.Form):
    name = forms.CharField(label='Название', max_length=30)
    date = forms.DateField(label='Дата')


class SetEventForm(forms.Form):
    student_id = forms.IntegerField(label="Студент")
    event_id = forms.IntegerField(label='Событие')

api/views/marks.py
import json

from django.http import HttpResponse
from datetime import date
from api.models import rMark
from journal.models import Mark, UserExtension, Lesson



def add_mark(request):
    value2marks = {
        '1': 1,
        '2': 2,
        '3': 3,
        '4': 4,
        '5': 5,
        'п': -1,
        'у': -2,
        'н': -3,
    }

    m = Mark()
    d = json.loads(request.body)
    lesson = Lesson.objects.get(id=d["lesson_id"])

    user = request.user
    try:
        ext = UserExtension.objects.get(user=user)
    except UserExtension.DoesNotExist:
        ext = None
    if ext and lesson:
        if not ext.squads.filter(userextension__squads__code=lesson.attendance.squad.code).exists():
            return HttpResponse(json.dumps({
                "error": "Этот пользователь не может изменять и создавать оценки для данного взвода",
            }))

        if ext.date_limit and lesson.attendance.date != date.today():
            return HttpResponse(json.dumps({
                "error": "Этот пользователь может изменять оценки только на текущую дату",
            }))

    req = rMark(
        value=value2marks.get(d["value"].lower()),
        id=d["mark_id"],
        student_id=d["student_id"],
    )

    if req.id:
        print("mark exists")
        m: Mark = Mark.objects.filter(id=req.id)[0]
        if req.value != '':
            m.val = req.value
            m.save()
        else:
            m.delete()
    else:
        print("new mark")
        m = Mark(
            student_id=req.student_id,
            val=req.value,
            lesson=lesson,
        )
        m.save()

    data = {
        "id": m.id,
    }
    print(m)
    return HttpResponse(json.dumps(data))

journal/views/attendance.py
from django.shortcuts import render
from journal.models import Attendance, UserExtension
from maintenance.helpers.named_tuple import namedtuple_wrapper
from journal import constants
from journal.managers.context import with_context, get_user_extension
from datetime import date

tAttendanceRestriction = namedtuple_wrapper(
    'tAttendanceRestriction',
    (
        'date_restricted',
        'date',
        'squads',
        'can_edit',
    )
)


def attendance(request):
    restrictions = None
    try:
        ext = UserExtension.objects.get(user=request.user)
    except UserExtension.DoesNotExist:
        ext = None
    if ext:
        allowed_squads = ext.squads.all()
        f = Attendance.objects.filter(squad__in=allowed_squads)
        restrictions = tAttendanceRestriction(
            date_restricted=ext.date_limit,
            date=date.today(),
            squads=allowed_squads,
            can_edit=ext.can_edit_attendance,
        )
    else:
        # all forms, no restrictions
        f = Attendance.objects.all()

    return render(
        request,
        "journal/attendance.html",
        with_context({
            "forms": f,
            "restrictions": restrictions
        })
    )


def edit_attendance(request, attendance_id):
    att: Attendance = Attendance.objects.filter(id=attendance_id)[0]
    context = {}
    ext = get_user_extension(request.user)
    if ext:
        if not ext.can_edit_attendance:
            context = {
                "error": "Этот пользователь не может изменять строевые записки"
            }
        elif ext.date_limit and att.date != date.today():
            context = {
                "error": "Этот пользователь не может изменять строевые записки за даты, отличающейся от текущей"
            }

    types = constants.ATT_TYPES
    if not context:
        context = {
            "students": att.students.all().order_by('student__last_name').prefetch_related('student'),
            "statuses": att.students.all().order_by('student__last_name').prefetch_related('student'),
            "attendance_types": types,
            "attendance_id": attendance_id,
            "squad_code": att.squad.code,
            "date": att.date,
        }

    return render(
                request,
                "journal/attendance_edit.html",
                with_context(context)
            )

journal/views/test.py
from django.shortcuts import render



def test(request):
    return render(request, "journal/index.html")

templates/journal/marks/marks_squad.html
{% extends 'base.html' %}

{% csrf_token %}
{% load static %}

{% static 'journal/hover.css' %}

{% block content %}
    {#    {% if cells and header and y_keys %}#}
    {#        all keys present#}
    {#    {% else %}#}
    {#        some keys not present#}
    {#    {% endif %}#}
    {% include 'journal/marks/table.html' %}
    {#    {% for mark in marks %}#}
    {#        <li> {{ mark.id }} {{ mark.date }} {{ mark.val }}#}
    {#            {{ mark.key.id }} {{ mark.key.display }} {{ mark.key.sort }}</li>#}
    {#    {% endfor %}#}
{% endblock %}


{% block javascript %}
    {{ block.super }}
    <script>

        let x_keys, y_keys, subject_id;

        x_keys = [
            {% for x in x_keys %}
                {
                    id: {{ x.id }},
                    display: "{{ x.display }}",
                    val: "{{ x.val }}",
                },
            {% endfor %}
        ];

        y_keys = [
            {% for y in y_keys %}
                {
                    id: {{ y.id }},
                    display: "{{ y.display }}",
                    val: "{{ y.val }}",
                },
            {% endfor %}
        ];
        {#console.log("x:", x_keys);#}
        {#console.log("y:", y_keys);#}
        subject_id = {{ subject_id }};
    </script>
    <script type="text/javascript" src="{% static 'common/js/input.js' %}"></script>
    <script type="text/javascript" src="{% static 'journal/marks/marks_squad.js' %}"></script>
    <link type="text/css" rel="stylesheet" href="{% static 'journal/marks/fixedColumns.bootstrap.min.css' %}"/>
{% endblock %}

templates/journal/marks/table.html
{% block table %}
    <button class="btn pull-right" data-toggle="modal" data-target="#modalLoginForm"><i class="fa fa-plus"></i> Добавить
        столбец
    </button>
    <table id="marks" class="table table-striped">
        <thead>
        <tr>
            <th class="col-xs-12 col-lg-12">
                {{ subject.name }}
            </th>
            {% for x in header %}
                <th>{{ x.display }}
                </th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for row in cells %}
            <tr>
                {% for elem in row %}
                    {% if forloop.counter == 1 %}
                        <th class="col-xs-12 col-lg-12">
                            <a href="{% url 'student' student_id=elem.id %}">{{ elem.display }}</a>
                        </th>
                    {% else %}
                        <td class="col-min">
                            <label>
                                <input class="mycell"
                                       type="text"

                                        {% if elem.val == -1 %}
                                       value="П"
                                       disabled
                                        {% elif elem.val == -2 %}
                                       value="У"
                                       disabled
                                        {% elif elem.val == -3 %}
                                       value="Н"
                                       disabled
                                        {% elif elem.val == None %}
                                       value=""
                                        {% else %}
                                       value="{{ elem.val }}"
                                        {% endif %}

                                       style="width:24px; height:24px;text-align: center;"
                                       name="{'x_index':{{ forloop.counter0 }}, 'y_key_id':{{ row.0.id }}, 'mark_id': '{{ elem.id }}' }"
                                />
                            </label>
                        </td>
                    {% endif %}
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <th></th>
            {% for x in header %}
                {% if x.comment %}
                    {#                    <th style="transform: rotate(90deg); padding-right: -15px;"> #}
                    <th>
                        {% if not x.exam_id %}
                            {{ x.comment }}
                        {% else %}
                            <a href="/admin/journal/exam/{{ x.exam_id }}/change">{{ x.comment }} ({{ x.exam_name }})</a>
                        {% endif %}
                    </th>
                {% else %}
                    <th>{{ x.display }}
                    </th>
                {% endif %}
            {% endfor %}
        </tr>

        </tfoot>
    </table>

{% endblock %}

{% block modal %}
    <div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header text-center">
                    <h4 class="modal-title w-100 font-weight-bold">Добавить столбец</h4>
                </div>
                <form action="/api/lessons/add" method="post">
                    <div class="modal-body mx-3">
                        {% csrf_token %}
                        {{ form }}
                        <div class="md-form mb-5">
                            <label data-error="wrong" data-success="right" for="att_id">Дата</label>
                            {#                            <input placeholder="Выберите дату" name="date" type="text" id="id_date" class="form-control datepicker">#}

                            <select id="attendance_id" name="attendance_id">
                                {% for t in attendance_list %}
                                    <option
                                            value="{{ t.id }}"
                                    >{{ t.date|date:"d-m-Y" }}</option>
                                {% endfor %}
                            </select>


                        </div>
                        <div class="md-form mb-4">
                            <label data-error="wrong" data-success="right" for="id_name">Название</label>
                            <input type="text" id="id_name" name="name" class="form-control">

                            <label for="id_squad_code"></label><input type="text" id="id_squad_code" name="squad_code"
                                                                      value="{{ squad_code }}" hidden>
                            <label for="id_subject_id"></label><input type="number" id="id_subject_id" name="subject_id"
                                                                      value="{{ subject_id }}" hidden>
                        </div>
                        {% if exam_list %}
                            <button class="btn btn-primary" type="button" data-toggle="collapse"
                                    data-target="#collapseExample" aria-expanded="false"
                                    aria-controls="collapseExample">
                                Добавить связь с экзаменом
                            </button>
                            <div class="collapse" id="collapseExample">
                                <div class="card card-body">
                                    <label for="exam">Экзамен</label>
                                    <select id="exam_id" name="exam_id">
                                        <option value="" selected>Выберите экзамен</option>
                                        {% for exam in exam_list %}
                                            <option value="{{ exam.id }}">{{ exam.display }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>

                        {% else %}
                            <button class="btn btn-primary disabled" type="button" data-toggle="tooltip"
                                    title="Для этого предмета не создано ни одного экзамена"
                                    data-target="#collapseExample" aria-expanded="false">
                                Добавить связь с экзаменом
                            </button>
                        {% endif %}
                    </div>
                    <div class="modal-footer d-flex justify-content-center">
                        {#                    TODO make proper form     #}
                        <button class="btn btn-default" type="submit" id="lessonFormSubmit">ОК</button>
                        <button class="btn btn-default" data-dismiss="modal">Отмена</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        $(function () {
            $('.datepicker').datetimepicker(
                {
                    format: 'DD-MM-YYYY',
                }
            );
        });
    </script>
{% endblock %}